language: ruby
cache:
  bundler: true
  directories:
  - EnergyPlus
os:
- linux
rvm:
- 2.3.3
env:
  matrix:
  - CHECK='ruby tests/ts_all_tests.rb'
  - CHECK='rubocop -D'
install:
- bundle install --path=vendor/bundle
script:
- "bundle exec $CHECK"
