language: ruby
cache:
  bundler: true
os:
- linux
rvm:
- 2.3.3
env:
  matrix:
  - CHECK='ruby tests/ts_all_tests.rb'
  - CHECK='rubocop -D'
install:
- bundle install --path=vendor/bundle
- sudo apt-get install -y --no-install-recommends gnuplot texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
script:
- "bundle exec $CHECK"
